version: '2'

services:
  sonarqube:
    image: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9002:9002"
    links:
      - postgres:db
    environment:
  ##    - SONARQUBE_JDBC_USERNAME=sonar
  ##    - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /leadsoft/project/SonarQube/plugins:/opt/sonarqube/extensions/plugins
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /leadsoft/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
